server:
  port: 9001
spring:
  application:
    name: DEPARTMENT-SERVICE
  h2:
    console.path: /h2-console
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url: http://127.0.0.1:9411/